import { Service } from '@angular/core';

@Service()
export class RootServices {
  public httpLink: string = 'https://esat.ae/wp-content/themes/ESAT/api/serverfile.php?a='; //'http:/localhost/esat/wp-content/themes/ESAT/api/serverfile.php?a=';
  public joblink: string = 'https://esat.ae/wp-content/themes/ESAT/api/jobs.php'; //'http:/localhost/esat/wp-content/themes/ESAT/api/jobs.php';
  //public httpLink: string = 'http:/localhost/esat/wp-json/wp/v2/pages/'; //-- To get Direct From Wordpress

  public apiLink: string = 'https://esat.ae/wp-content/themes/ESAT/api'; //'http:/localhost/esat/wp-content/themes/ESAT/api';
  public contactoption: any = 0;
  public version: any = '18012024';
  public optionValues: any = [];
  public MasterUser: any = [];
  public MasterUserId: string = '';
  public returnValue: string = '';
  public webData: any = [];
  public modHide: boolean = false;
  public svgHide: boolean = false;
  public customCart: any = [];
  public projects: any;
  public beforeCart: any = [];
  public Cart: any = [];
  public guest: any = [];
  public selectedLink: any = '';
  public overallproduct: any[] | undefined;
  public allModule = [
    {
      id: 'iovr',
      name: '<span>Complete Management</span>',
      shortname: 'Complete Management ',
      visible: true,
      disable: false,
      icon: 'ind-complete',
      bt: 'industry',
      pagelink: '1545',
      link: 'swindoverall',
      thumblink: 'esat-project-solution-page-image.jpg',
      selected: "{['am', 'pm', 'fim', 'py', 'hcm', 'sm', 'lm', 'cont']}",
      brief: 'The ESAT Business Enterprise Edition is powerful, flexible and easy to use.',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'ifm',
      name: '<span>Facility Management</span>',
      shortname: 'Facility Management ',
      visible: true,
      disable: false,
      icon: 'ind-facilituy',
      bt: 'industry',
      pagelink: '344',
      link: 'swindfacility',
      thumblink: 'facility.jpg',
      selected: "{['am', 'fim', 'hcm', 'lm', 'cont', 'pm', 'py', 'sm', 'crm', 'fm', 'hrm',]}",
      brief:
        'ESATs Facility Management Solutions simplifies complex operations, aids in cost reduction and improves efficiencies',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'irem',
      name: '<span>Real Estate Management</span>',
      shortname: 'Real Estate Management ',
      visible: true,
      disable: false,
      icon: 'ind-realestate',
      bt: 'industry',
      pagelink: '356',
      link: 'swindremang',
      thumblink: 'esat-realestate-solution-page-image.jpg',
      selected: "{['am', 'fim', 'hcm', 'lm', 'cont', 'pm', 'py', 'sm', 'rem']}",
      brief:
        'This maintains and manages the entire business process of a real estate developer or a broker from end to end',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'icons',
      name: '<span>Construction Management</span>',
      shortname: 'Construction Management ',
      visible: true,
      disable: false,
      icon: 'ind-construction',
      bt: 'industry',
      pagelink: '788',
      link: 'swindconst',
      thumblink: 'Construction.jpg',
      selected: "{['am', 'fim', 'hcm', 'lm', 'cont', 'pm', 'py', 'sm', 'prm']}",
      brief:
        'You will have better control over your Employees, Assets, Materials, Subcontracts, Equipment’s etc. increasing your efficiency and profitability.',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'imf',
      name: '<span>Manufacturing Management</span>',
      shortname: 'Manufacturing Management',
      visible: true,
      disable: false,
      icon: 'moduleicontask_icon',
      bt: 'industry',
      pagelink: '788',
      link: 'swindmanufacturing',
      thumblink: 'esat-mng-solution-page-image.jpg',
      selected: "{['am', 'fim', 'hcm', 'lm', 'cont', 'pm', 'py', 'sm', 'imf']}",
      brief:
        'ESAT Manufacturing Management System recognized the need of manufacturers to operate seamlessly across multiple manufacturing modes.',
      status: false,
      countComp: '01',
      countUser: '01',
    },

    {
      id: 'ifl',
      name: '<span>Fleet Management</span>',
      shortname: 'Fleet Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconfl_icon',
      bt: 'mod',
      pagelink: '1534',
      link: 'swindfleetmanagement',
      thumblink: 'esat-fleet.jpg',
      selected: "{['am', 'fim', 'hcm', 'lm', 'cont', 'pm', 'py', 'sm', 'imf']}",
      brief: 'A fleet Management System (WMS) is used to easily handle all the Fleet activities.',
      status: false,
      countComp: '01',
      countUser: '01',
      src: 'assets/images/fleet.svg',
      modcls: 'modcls',
    },

    {
      id: 'ish',
      name: '<span>Shipment Management</span>',
      shortname: 'Shipment Management',
      visible: true,
      disable: false,
      icon: 'moduleiconsh_icon',
      bt: 'mod',
      pagelink: '1534',
      link: 'swindshipmentmanagement',
      thumblink: 'esat-shipment.jpg',
      selected: "{['am', 'fim', 'hcm', 'lm', 'cont', 'pm', 'py', 'sm', 'imf']}",
      brief:
        'The shipment Solution serves as the company’s way to remunerate each employee for the services they provide for the company.',
      status: false,
      countComp: '01',
      countUser: '01',
      src: 'assets/images/quality.svg',
      modcls: 'modcls',
    },

    {
      id: 'ire',
      name: '<span>Retail & POS Management</span>',
      shortname: 'Retail Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconre_icon',
      bt: 'mod',
      pagelink: '356',
      link: 'swindretailpos',
      thumblink: 'esat-retail.jpg',
      selected: "{['am', 'fim', 'hcm', 'lm', 'cont', 'pm', 'py', 'sm', 'imf']}",
      brief:
        'The Retail Solution serves as the company’s way to remunerate each employee for the services they provide for the company.',
      status: false,
      countComp: '01',
      countUser: '01',
      src: 'assets/images/quality.svg',
      modcls: 'modcls',
    },
    {
      id: 'iwa',
      name: '<span>Warehouse Management</span>',
      shortname: 'Warehouse Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconwa_icon',
      bt: 'mod',
      pagelink: '1534',
      link: 'swindwarehouse',
      thumblink: 'esat-warehouse.jpg',
      selected: "{['am', 'fim', 'hcm', 'lm', 'cont', 'pm', 'py', 'sm', 'imf']}",
      brief:
        'A Warehouse Management System (WMS) is used to easily handle all the Warehouse activities.',
      status: false,
      countComp: '01',
      countUser: '01',
      src: 'assets/images/warehouse.svg',
      modcls: 'modcls',
    },

    {
      id: 'iCm',
      name: '<span>CMMS Management</span>',
      shortname: 'Cmms Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconwcm_icon',
      bt: 'mod',
      pagelink: '1534',
      link: 'swindcmms',
      thumblink: 'esat-cmms.jpg',
      brief: 'A cmms Management System (WMS) is used to easily handle all the Fleet activities.',
      status: false,
      countComp: '01',
      countUser: '01',
      src: 'assets/images/cmms.svg',
      modcls: 'modcls',
    },
  ];

  public allmoduleList: any = [
    {
      id: 'am',
      name: '<span>Fixed Asset Management</span> ',
      trngname: '<span>Fixed Asset Mgmt</span>',
      shortname: 'Asset Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconassets_icon',
      bt: 'mod',
      pagelink: '340',
      link: 'assert',
      trainglink: 'traingasset',
      thumblink: 'assert.jpg',
      brief:
        'Efficiently manage the entire asset lifecycle with world-class enterprise asset management software from ESAT',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'crm',
      name: '<span>Customer Relationship Management</span>',
      trngname: '<span>CRM Mgmt</span>',
      shortname: 'Customer Relationship Management',
      visible: true,
      disable: false,
      icon: 'moduleiconcrm_icon',
      bt: 'mod',
      pagelink: '342',
      link: 'crm',
      trainglink: 'trainingcrm',
      thumblink: 'crmimg.jpg',
      brief:
        'The CRM Solution provides all sectors of professionals with complete customer intelligence to manage relationships and customer-related processes.',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'fm',
      name: '<span>Facility & Service Management</span>',
      trngname: '<span>Facility & Service Mgmt</span>',
      shortname: 'Facility Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconfacilitymanagement_icon',
      bt: 'mod',
      pagelink: '344',
      link: 'facility',
      trainglink: 'trainingfacility',
      thumblink: 'facility.jpg',
      brief:
        'ESATs Facility Management Solutions simplifies complex operations, aids in cost reduction and improves efficiencies',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'fim',
      name: '<span>Finance & Accounts Management</span>',
      trngname: '<span>Finance & Accounts Mgmt</span>',
      shortname: 'Finance Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconfinancemanagement',
      bt: 'mod',
      pagelink: '346',
      link: 'finance',
      trainglink: 'trainingfinance',
      thumblink: 'finance.jpg',
      brief:
        'ESATs Finance & Accounts Management Solution helps finance teams be more productive and serves business managers with innovative best practices.',
      status: false,
      countComp: '01',
      countUser: '01',
    },

    {
      id: 'hrm',
      name: '<span>Human Resource Management</span>',
      trngname: '<span>Human Resource Mgmt</span>',
      shortname: 'Human Resource Management',
      visible: true,
      disable: false,
      icon: 'moduleiconhrm_icon',
      bt: 'mod',
      pagelink: '1548',
      link: 'hrm',
      trainglink: 'traininghrm',
      thumblink: 'hrm.jpg',
      brief:
        'ESAT HR Management is an integrated solution desinged to facilitate HR operations by reducing time intensive administrative task.',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'hcm',
      name: '<span>Human Capital Management</span>',
      trngname: '<span>Human Capital Mgmt</span>',
      shortname: 'Human Capital Management',
      visible: true,
      disable: false,
      icon: 'moduleiconhcm_icon',
      bt: 'mod',
      pagelink: '348',
      link: 'hcm',
      trainglink: 'traininghcm',
      thumblink: 'hcm.jpg',
      brief:
        'Our HCM Solutions offer a complete, compliant and modern HCM solution to manage the modern workforce.',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'py',
      name: '<span>Payroll Management</span>',
      trngname: '<span>Payroll Mgmt</span>',
      shortname: 'Payroll Management ',
      visible: true,
      disable: false,
      icon: 'moduleicon_payrollicon',
      bt: 'mod',
      pagelink: '1481',
      link: 'payrole',
      trainglink: 'trainingpayroll',
      thumblink: 'esat-payroll.png',
      brief:
        'The Payroll Solution serves as the company’s way to remunerate each employee for the services they provide for the company.',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'cont',
      name: '<span>Contract Management</span>',
      trngname: '<span>Contract Mgmt</span>',
      shortname: 'Contract Management',
      visible: true,
      disable: false,
      icon: 'moduleiconcont_icon',
      bt: 'mod',
      pagelink: '1550',
      link: 'contact-mng',
      trainglink: 'trainingcontract',
      thumblink: 'contract.jpg',
      brief:
        'ESAT Contract Management Easy-to-use subcontract entry to manage the details of the contract',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'lm',
      name: '<span>Inventory Management</span>',
      trngname: '<span>Inventory Mgmt</span>',
      shortname: 'Inventory Management',
      visible: true,
      disable: false,
      icon: 'moduleiconlogistic_icon',
      bt: 'mod',
      pagelink: '350',
      link: 'logistics',
      trainglink: 'traininginventory',
      thumblink: 'esat-logistic-solution-page-image.jpg',
      brief:
        'The Inventory Management Solution is a tool to manage, control and keep accurate records of inventory items of the organization',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'pm',
      name: '<span>Procurement Management</span>',
      trngname: '<span>Procurement Mgmt</span>',
      shortname: 'Procurement Management',
      visible: true,
      disable: false,
      icon: 'moduleiconprocurement_icon',
      bt: 'mod',
      pagelink: '352',
      link: 'procurement',
      trainglink: 'trainingprocurement',
      thumblink: 'esat-procurement-solution-page-image.jpg',
      brief: 'Our Procurement Solutions use modern best practices and data-driven procurement.',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'sm',
      name: '<span>Sales Management</span>',
      trngname: '<span>Sales Mgmt</span>',
      shortname: 'Sales Management ',
      visible: true,
      disable: false,
      icon: 'font-20',
      bt: 'mod',
      pagelink: '358',
      link: 'salesmanagement',
      trainglink: 'trainingsales',
      thumblink: 'esat-sales-solution-page-image.jpg',
      brief: 'Accelerate productivity and sales performance with our Sales Management Solutions.',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'prm',
      name: '<span>Budget & Project Management </span>',
      trngname: '<span>Budget & Project Mgmt</span>',
      shortname: 'Budget and Project Management ',
      visible: true,
      disable: false,
      icon: 'icon-project',
      bt: 'mod',
      pagelink: '354',
      link: 'budject',
      trainglink: 'trainingbudget',
      thumblink: 'esat-project-solution-page-image.jpg',
      brief: 'Find out how to accurately and easily track time and labor for project tasks.',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'rem',
      name: '<span>Real Estate Management</span>',
      trngname: '<span>Real Estate Mgmt</span>',
      shortname: 'Real Estate Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconrealestate_icon',
      bt: 'mod',
      pagelink: '356',
      link: 'realestate',
      trainglink: 'trainingrealestate',
      thumblink: 'esat-realestate-solution-page-image.jpg',
      brief:
        'This maintains and manages the entire business process of a real estate developer or a broker from end to end',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'mf',
      name: '<span>Manufacturing Management</span>',
      trngname: '<span>Manufacturing Mgmt</span>',
      shortname: 'Manufacturing Management',
      visible: true,
      disable: false,
      icon: 'moduleicontask_icon',
      bt: 'mod',
      pagelink: '1534',
      link: 'manufacturing',
      trainglink: 'trainingmanufacturing',
      thumblink: 'esat-mng-solution-page-image.jpg',
      brief:
        'ESAT Manufacturing Management System recognized the need of manufacturers to operate seamlessly across multiple manufacturing modes.',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 'od',
      name: '<span>Organization Development</span>',
      trngname: '<span>Organization Mgmt</span>',
      shortname: 'Organization Development',
      visible: true,
      disable: false,
      icon: 'odesatodmodicon',
      bt: 'mod',
      pagelink: '1481',
      link: 'od',
      trainglink: 'trainingorganization',
      thumblink: 'esat-od-solution-page-image.jpg',
      brief:
        'ESAT Organization Developement system provide a uniform and consistent method to be followed by employees working in the Orgnisation.',
      status: false,
      countComp: '01',
      countUser: '01',
    },
    {
      id: 're',
      name: '<span>Retail & POS Management</span>',
      trngname: '<span>Retail & POS Mgmt</span>',
      shortname: 'Retail Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconre_icon',
      bt: 'mod',
      pagelink: '356',
      link: 'retail',
      trainglink: 'trainingretail',
      thumblink: 'esat-retail.jpg',
      brief:
        'The Retail Solution serves as the company’s way to remunerate each employee for the services they provide for the company.',
      status: false,
      countComp: '01',
      countUser: '01',
      src: 'assets/images/quality.svg',
      modcls: 'modcls',
    },
    {
      id: 'wa',
      name: '<span>Warehouse Management</span>',
      trngname: '<span>Warehouse Mgmt</span>',
      shortname: 'Warehouse Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconwa_icon',
      bt: 'mod',
      pagelink: '1534',
      link: 'warehouse',
      trainglink: 'trainingwarehouse',
      thumblink: 'esat-warehouse.jpg',
      brief:
        'A Warehouse Management System (WMS) is used to easily handle all the Warehouse activities.',
      status: false,
      countComp: '01',
      countUser: '01',
      src: 'assets/images/warehouse.svg',
      modcls: 'modcls',
    },
    {
      id: 'fl',
      name: '<span>Fleet Management</span>',
      trngname: '<span>Fleet Mgmt</span>',
      shortname: 'Fleet Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconfl_icon',
      bt: 'mod',
      pagelink: '1534',
      link: 'fleet',
      trainglink: 'trainingfleet',
      thumblink: 'esat-fleet.jpg',
      brief: 'A fleet Management System (FMS) is used to easily handle all the Fleet activities.',
      status: false,
      countComp: '01',
      countUser: '01',
      src: 'assets/images/fleet.svg',
      modcls: 'modcls',
    },

    {
      id: 'Cm',
      name: '<span>CMMS Management</span>',
      trngname: '<span>CMMS Mgmt</span>',
      shortname: 'Cmms Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconwcm_icon',
      bt: 'mod',
      pagelink: '1534',
      link: 'cmms',
      trainglink: 'trainingcmms',
      thumblink: 'esat-cmms.jpg',
      brief: 'A cmms Management System (WMS) is used to easily handle all the Fleet activities.',
      status: false,
      countComp: '01',
      countUser: '01',
      src: 'assets/images/cmms.svg',
      modcls: 'modcls',
    },

    // {
    //     "id": "it",
    //     "name": "<span>IT</span><br/> Management",
    //     "shortname": "IT Management",
    //     "visible": true,
    //     "disable": false,
    //     "icon": "moduleiconit_icon",
    //     "bt": "mod",
    //     "pagelink": "1481",
    //     "link": "IT",
    //     "thumblink": "esat-IT.jpg",
    //     "brief": "The IT Solution serves as the company’s way to remunerate each employee for the services they provide for the company.",
    //     "status": false,
    //     "countComp": "01",
    //     "countUser": "01",
    //     "src": "assets/images/quality.svg",
    //     "modcls": "modcls"
    // },
    {
      id: 'sh',
      name: '<span>Shipment Management</span>',
      trngname: '<span>Shipment Mgmt</span>',
      shortname: 'shipment Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconsh_icon',
      bt: 'mod',
      pagelink: '1534',
      link: 'shipment',
      trainglink: 'trainingshipment',
      thumblink: 'esat-shipment.jpg',
      brief:
        'The shipment Solution serves as the company’s way to remunerate each employee for the services they provide for the company.',
      status: false,
      countComp: '01',
      countUser: '01',
      src: 'assets/images/quality.svg',
      modcls: 'modcls',
    },
    {
      id: 'qa',
      name: '<span>Quality Management</span>',
      trngname: '<span>Quality Mgmt</span>',
      shortname: 'quality Management ',
      visible: true,
      disable: false,
      icon: 'moduleiconqa_icon',
      bt: 'mod',
      pagelink: '354',
      link: 'quality',
      trainglink: 'trainingquality',
      thumblink: 'esat-quality.jpg',
      brief:
        'The Quality Solution serves as the company’s way to remunerate each employee for the services they provide for the company.',
      status: false,
      countComp: '01',
      countUser: '01',
      src: 'assets/images/quality.svg',
      modcls: 'modcls',
    },
    // {
    //     "id": "lg",
    //     "name": "<span>legal</span><br/> Management",
    //     "shortname": "legal Management ",
    //     "visible": true,
    //     "disable": false,
    //     "icon": "moduleiconlg_icon",
    //     "bt": "mod",
    //     "pagelink": "352",
    //     "link": "legal",
    //     "thumblink": "esat-legal.jpg",
    //     "brief": "The Legal Solution serves as the company’s way to remunerate each employee for the services they provide for the company.",
    //     "status": false,
    //     "countComp": "01",
    //     "countUser": "01",
    //     "src": "assets/images/quality.svg",
    //     "modcls": "modcls"
    // },
  ];
  apiUrl: any;
  refreshVisible() {
    this.allmoduleList.forEach((element: { visible: boolean }) => {
      element.visible = true;
    });
    this.allModule.forEach((element) => {
      element.visible = true;
    });
  }
}
